

// Template definitions
export const templates: any = [
  // Contact Form Template
  {
    id: "template-contact",
    title: "Contact Form",
    description: "A simple contact form to collect user inquiries",
    coverImage: "https://images.pexels.com/photos/15586509/pexels-photo-15586509/free-photo-of-pascoa-ovos-decoracao-celebracao.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name",
        type: "text",
        label: "Name",
        placeholder: "Enter your name",
        required: true,
      },
      {
        id: "field-email",
        type: "email",
        label: "Email",
        placeholder: "Enter your email",
        required: true,
        helpText: "We'll never share your email with anyone else",
      },
      {
        id: "field-subject",
        type: "text",
        label: "Subject",
        placeholder: "What is your message about?",
        required: true,
      },
      {
        id: "field-message",
        type: "textarea",
        label: "Message",
        placeholder: "Enter your message here",
        required: true,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Send Message",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "default",
    },
    settings: {
      successMessage: "Thank you for your message! We'll get back to you soon.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "business",
    createdAt: "2023-09-15T10:00:00Z",
    complexity: "simple",
  },

  // Event Registration Template
  {
    id: "template-event",
    title: "Event Registration",
    description: "Collect registrations for your next event",
    coverImage: "https://images.pexels.com/photos/20805084/pexels-photo-20805084/free-photo-of-comida-alimento-refeicao-madeira.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
        helpText: "We'll send the event details to this email",
      },
      {
        id: "field-phone",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: false,
      },
      {
        id: "field-tickets",
        type: "number",
        label: "Number of Tickets",
        placeholder: "How many tickets do you need?",
        required: true,
      },
      {
        id: "field-dietary",
        type: "select",
        label: "Dietary Restrictions",
        placeholder: "Select if applicable",
        required: false,
        options: ["None", "Vegetarian", "Vegan", "Gluten-Free", "Other"],
      },
      {
        id: "field-notes",
        type: "textarea",
        label: "Special Requests",
        placeholder: "Any special requests or notes?",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Register Now",
      variant: "default",
      size: "lg",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f8f9fa",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "You're registered! Check your email for confirmation details.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "events",
    createdAt: "2023-10-05T14:30:00Z",
    complexity: "medium",
  },

  // Feedback Survey Template
  {
    id: "template-feedback",
    title: "Feedback Survey",
    description: "Collect feedback about your product or service",
    coverImage: "https://images.pexels.com/photos/28820302/pexels-photo-28820302/free-photo-of-coelho-selvagem-em-pastagens-rurais-suecas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-rating",
        type: "select",
        label: "How would you rate your experience?",
        required: true,
        options: ["Excellent", "Good", "Average", "Below Average", "Poor"],
      },
      {
        id: "field-recommend",
        type: "radio",
        label: "Would you recommend us to others?",
        required: true,
        options: ["Definitely", "Maybe", "No"],
      },
      {
        id: "field-features",
        type: "checkbox",
        label: "Which features do you like the most?",
        required: false,
        options: ["Ease of use", "Design", "Performance", "Customer support", "Price"],
      },
      {
        id: "field-improvements",
        type: "textarea",
        label: "What could we improve?",
        placeholder: "Please share your suggestions",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Feedback",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your valuable feedback!",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2023-08-20T09:15:00Z",
    complexity: "medium",
  },

  // Newsletter Signup Template
  {
    id: "template-newsletter",
    title: "Newsletter Signup",
    description: "Grow your email list with this simple signup form",
    coverImage: "https://images.pexels.com/photos/158832/giraffe-reticulated-giraffe-neck-beautiful-158832.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name",
        type: "text",
        label: "First Name",
        placeholder: "Enter your first name",
        required: false,
      },
      {
        id: "field-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
        helpText: "We'll never share your email with anyone else",
      },
      {
        id: "field-interests",
        type: "checkbox",
        label: "I'm interested in",
        required: false,
        options: ["Product updates", "Industry news", "Tips & tutorials", "Special offers"],
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Subscribe",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "default",
    },
    settings: {
      successMessage: "Thanks for subscribing to our newsletter!",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "marketing",
    featured: true,
    createdAt: "2023-11-10T16:45:00Z",
    complexity: "simple",
  },

  // Microsoft-inspired Survey Template
  {
    id: "template-ms-survey",
    title: "Microsoft-style Feedback",
    description: "Clean, professional survey inspired by Microsoft Forms",
    coverImage:
      "https://images.pexels.com/photos/206770/pexels-photo-206770.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-satisfaction",
        type: "select",
        label: "How satisfied are you with our product?",
        required: true,
        options: ["Very satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very dissatisfied"],
      },
      {
        id: "field-usage",
        type: "radio",
        label: "How often do you use our product?",
        required: true,
        options: ["Daily", "Weekly", "Monthly", "Rarely", "First time"],
      },
      {
        id: "field-features-ms",
        type: "checkbox",
        label: "Which features are most important to you?",
        required: true,
        options: ["Ease of use", "Performance", "Integration", "Security", "Support"],
      },
      {
        id: "field-nps",
        type: "number",
        label: "On a scale of 0-10, how likely are you to recommend us?",
        placeholder: "Enter a number from 0 to 10",
        required: true,
        validation: {
          min: 0,
          max: 10,
        },
      },
      {
        id: "field-feedback",
        type: "textarea",
        label: "What could we do to improve your experience?",
        placeholder: "Your feedback helps us improve",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Feedback",
      variant: "default",
      size: "default",
      fullWidth: false,
      rounded: false,
      position: "right",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f0f0f0",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your feedback! Your input helps us improve our products.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "business",
    featured: true,
    createdAt: "2023-12-01T11:20:00Z",
    complexity: "medium",
  },

  // Google-inspired Form Template
  {
    id: "template-google-form",
    title: "Google-style Form",
    description: "Clean, minimal form inspired by Google Forms",
    coverImage:
      "https://images.pexels.com/photos/460961/pexels-photo-460961.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name-google",
        type: "text",
        label: "Name",
        placeholder: "Your answer",
        required: true,
      },
      {
        id: "field-email-google",
        type: "email",
        label: "Email",
        placeholder: "Your email",
        required: true,
      },
      {
        id: "field-education",
        type: "select",
        label: "Highest level of education",
        required: true,
        options: ["High School", "Associate's Degree", "Bachelor's Degree", "Master's Degree", "Doctorate", "Other"],
      },
      {
        id: "field-experience",
        type: "radio",
        label: "Years of experience",
        required: true,
        options: ["0-1 years", "2-5 years", "6-10 years", "10+ years"],
      },
      {
        id: "field-skills",
        type: "checkbox",
        label: "Skills",
        required: true,
        options: ["Programming", "Design", "Marketing", "Communication", "Leadership"],
      },
      {
        id: "field-additional",
        type: "textarea",
        label: "Additional information",
        placeholder: "Your answer",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit",
      variant: "default",
      size: "default",
      fullWidth: false,
      rounded: false,
      position: "right",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#ffffff",
      inputStyle: "underlined",
    },
    settings: {
      successMessage: "Your response has been recorded.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "education",
    featured: true,
    createdAt: "2023-11-15T13:40:00Z",
    complexity: "medium",
  },

  // Typeform-inspired Conversational Form
  {
    id: "template-typeform",
    title: "Conversational Form",
    description: "Engaging, conversational form inspired by Typeform",
    coverImage:
      "https://images.pexels.com/photos/998708/pexels-photo-998708.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-welcome",
        type: "text",
        label: "Hi there! What's your name?",
        placeholder: "Type your name...",
        required: true,
      },
      {
        id: "field-email-typeform",
        type: "email",
        label: "Nice to meet you! What's your email address?",
        placeholder: "your.email@example.com",
        required: true,
      },
      {
        id: "field-reason",
        type: "select",
        label: "What brings you here today?",
        required: true,
        options: ["Just browsing", "Looking for information", "Want to make a purchase", "Need support", "Other"],
      },
      {
        id: "field-interest-level",
        type: "radio",
        label: "How interested are you in our product?",
        required: true,
        options: ["Very interested", "Somewhat interested", "Neutral", "Not very interested"],
      },
      {
        id: "field-story",
        type: "textarea",
        label: "Tell us your story. What are you hoping to achieve?",
        placeholder: "I'm looking to...",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Continue →",
      variant: "default",
      size: "lg",
      fullWidth: false,
      rounded: true,
      position: "right",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f2f2f7",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "Thanks for sharing! We'll be in touch soon.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "marketing",
    featured: true,
    createdAt: "2023-10-25T09:30:00Z",
    complexity: "advanced",
  },

  // Job Application Form
  {
    id: "template-job-application",
    title: "Job Application",
    description: "Professional form for collecting job applications",
    coverImage: "https://images.pexels.com/photos/10015159/pexels-photo-10015159.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-full-name",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-email-job",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-phone-job",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
      },
      {
        id: "field-position",
        type: "select",
        label: "Position Applied For",
        required: true,
        options: [
          "Software Developer",
          "UX Designer",
          "Product Manager",
          "Marketing Specialist",
          "Customer Support",
          "Other",
        ],
      },
      {
        id: "field-experience-job",
        type: "textarea",
        label: "Relevant Experience",
        placeholder: "Briefly describe your relevant experience",
        required: true,
      },
      {
        id: "field-start-date",
        type: "date",
        label: "Available Start Date",
        required: true,
      },
      {
        id: "field-resume",
        type: "file",
        label: "Upload Resume/CV",
        required: true,
        helpText: "PDF, DOC, or DOCX formats accepted (max 5MB)",
      },
      {
        id: "field-cover-letter",
        type: "textarea",
        label: "Cover Letter",
        placeholder: "Why are you interested in this position?",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Application",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your application! We will review it and contact you soon.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "business",
    createdAt: "2023-09-05T15:20:00Z",
    complexity: "advanced",
  },

  // Course Evaluation Form
  {
    id: "template-course-evaluation",
    title: "Course Evaluation",
    description: "Gather feedback about educational courses",
    coverImage: "https://images.pexels.com/photos/751050/pexels-photo-751050.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-course-name",
        type: "text",
        label: "Course Name",
        placeholder: "Enter the course name",
        required: true,
      },
      {
        id: "field-instructor",
        type: "text",
        label: "Instructor Name",
        placeholder: "Enter the instructor's name",
        required: true,
      },
      {
        id: "field-semester",
        type: "select",
        label: "Semester",
        required: true,
        options: ["Fall 2023", "Spring 2024", "Summer 2024", "Fall 2024"],
      },
      {
        id: "field-content-rating",
        type: "radio",
        label: "How would you rate the course content?",
        required: true,
        options: ["Excellent", "Good", "Average", "Below Average", "Poor"],
      },
      {
        id: "field-instructor-rating",
        type: "radio",
        label: "How would you rate the instructor?",
        required: true,
        options: ["Excellent", "Good", "Average", "Below Average", "Poor"],
      },
      {
        id: "field-difficulty",
        type: "radio",
        label: "How difficult was this course?",
        required: true,
        options: ["Very Easy", "Easy", "Moderate", "Difficult", "Very Difficult"],
      },
      {
        id: "field-improvements",
        type: "textarea",
        label: "What improvements would you suggest for this course?",
        placeholder: "Your suggestions...",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Evaluation",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "default",
    },
    settings: {
      successMessage: "Thank you for your feedback! Your input helps us improve our courses.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "education",
    createdAt: "2023-08-10T10:15:00Z",
    complexity: "medium",
  },

  // E-commerce Product Survey
  {
    id: "template-ecommerce-survey",
    title: "Product Feedback Survey",
    description: "Collect customer feedback about your products",
    coverImage:
      "https://images.pexels.com/photos/5632402/pexels-photo-5632402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-product-name",
        type: "select",
        label: "Which product did you purchase?",
        required: true,
        options: ["Product A", "Product B", "Product C", "Product D", "Other"],
      },
      {
        id: "field-purchase-date",
        type: "date",
        label: "When did you purchase the product?",
        required: true,
      },
      {
        id: "field-satisfaction",
        type: "radio",
        label: "How satisfied are you with your purchase?",
        required: true,
        options: ["Very satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very dissatisfied"],
      },
      {
        id: "field-quality-rating",
        type: "select",
        label: "How would you rate the quality of the product?",
        required: true,
        options: ["Excellent", "Good", "Average", "Below Average", "Poor"],
      },
      {
        id: "field-value-rating",
        type: "select",
        label: "How would you rate the value for money?",
        required: true,
        options: ["Excellent", "Good", "Average", "Below Average", "Poor"],
      },
      {
        id: "field-improvements",
        type: "textarea",
        label: "What improvements would you suggest for this product?",
        placeholder: "Your suggestions...",
        required: false,
      },
      {
        id: "field-recommend",
        type: "radio",
        label: "Would you recommend this product to others?",
        required: true,
        options: ["Definitely", "Probably", "Not sure", "Probably not", "Definitely not"],
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Feedback",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f9f9f9",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "Thank you for your feedback! We appreciate your input.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "ecommerce",
    createdAt: "2024-01-15T14:30:00Z",
    complexity: "medium",
  },

  // Donation Form
  {
    id: "template-donation",
    title: "Donation Form",
    description: "Collect donations for your nonprofit organization",
    coverImage:
      "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-donor-name",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-donor-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
        helpText: "We'll send your donation receipt to this email",
      },
      {
        id: "field-donation-amount",
        type: "select",
        label: "Donation Amount",
        required: true,
        options: ["$10", "$25", "$50", "$100", "$250", "Other"],
      },
      {
        id: "field-custom-amount",
        type: "number",
        label: "Custom Amount ($)",
        placeholder: "Enter amount",
        required: false,
        helpText: "If you selected 'Other' above, please specify the amount",
      },
      {
        id: "field-recurring",
        type: "radio",
        label: "Would you like to make this a recurring donation?",
        required: true,
        options: ["One-time donation", "Monthly recurring", "Quarterly recurring", "Annual recurring"],
      },
      {
        id: "field-in-honor",
        type: "text",
        label: "In Honor/Memory of",
        placeholder: "Optional: Enter name",
        required: false,
      },
      {
        id: "field-comments",
        type: "textarea",
        label: "Comments",
        placeholder: "Any additional information you'd like to share",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Complete Donation",
      variant: "default",
      size: "lg",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f5f5f5",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your generous donation! A receipt has been sent to your email.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "nonprofit",
    createdAt: "2024-02-05T11:45:00Z",
    complexity: "advanced",
    featured: true,
  },

  // Restaurant Reservation Form
  {
    id: "template-restaurant-reservation",
    title: "Restaurant Reservation",
    description: "Take online reservations for your restaurant",
    coverImage:
      "https://images.pexels.com/photos/67468/pexels-photo-67468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-customer-name",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-customer-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-customer-phone",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        helpText: "We'll send a confirmation text to this number",
      },
      {
        id: "field-reservation-date",
        type: "date",
        label: "Reservation Date",
        required: true,
      },
      {
        id: "field-reservation-time",
        type: "select",
        label: "Reservation Time",
        required: true,
        options: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM"],
      },
      {
        id: "field-party-size",
        type: "select",
        label: "Party Size",
        required: true,
        options: [
          "1 person",
          "2 people",
          "3 people",
          "4 people",
          "5 people",
          "6 people",
          "7 people",
          "8 people",
          "9+ people (please specify in notes)",
        ],
      },
      {
        id: "field-special-occasion",
        type: "checkbox",
        label: "Special Occasion?",
        required: false,
        options: ["Birthday", "Anniversary", "Business Meeting", "Other"],
      },
      {
        id: "field-special-requests",
        type: "textarea",
        label: "Special Requests",
        placeholder: "Any dietary restrictions or special requests?",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Book Reservation",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f8f8f8",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Your reservation has been received! We'll send a confirmation to your email and phone shortly.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "business",
    createdAt: "2024-01-20T16:15:00Z",
    complexity: "medium",
  },

  // Webinar Registration Form
  {
    id: "template-webinar",
    title: "Webinar Registration",
    description: "Collect registrations for your upcoming webinar or online event",
    coverImage:
      "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-attendee-name",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-attendee-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
        helpText: "We'll send webinar access details to this email",
      },
      {
        id: "field-company",
        type: "text",
        label: "Company/Organization",
        placeholder: "Enter your company name",
        required: false,
      },
      {
        id: "field-job-title",
        type: "text",
        label: "Job Title",
        placeholder: "Enter your job title",
        required: false,
      },
      {
        id: "field-industry",
        type: "select",
        label: "Industry",
        required: true,
        options: ["Technology", "Healthcare", "Education", "Finance", "Manufacturing", "Retail", "Other"],
      },
      {
        id: "field-how-heard",
        type: "select",
        label: "How did you hear about this webinar?",
        required: false,
        options: ["Email", "Social Media", "Search Engine", "Colleague", "Website", "Other"],
      },
      {
        id: "field-questions",
        type: "textarea",
        label: "Questions for the presenter",
        placeholder: "Any questions you'd like addressed during the webinar?",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Register Now",
      variant: "default",
      size: "lg",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f0f4f8",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "You're registered! Check your email for webinar access details.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "marketing",
    createdAt: "2024-02-15T13:20:00Z",
    complexity: "medium",
  },

  // Customer Satisfaction Survey (CSAT)
  {
    id: "template-csat",
    title: "Customer Satisfaction Survey",
    description: "Measure customer satisfaction with your product or service",
    coverImage: "https://images.pexels.com/photos/27591755/pexels-photo-27591755/free-photo-of-animal-bicho-animal-de-estimacao-pet.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-customer-name",
        type: "text",
        label: "Name",
        placeholder: "Enter your name",
        required: false,
        helpText: "Optional: You can submit this survey anonymously",
      },
      {
        id: "field-customer-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: false,
        helpText: "Optional: Provide your email if you'd like us to follow up",
      },
      {
        id: "field-product-service",
        type: "select",
        label: "Which product or service are you providing feedback on?",
        required: true,
        options: ["Product A", "Product B", "Service A", "Service B", "Customer Support", "Other"],
      },
      {
        id: "field-satisfaction-rating",
        type: "radio",
        label: "How satisfied are you with our product/service?",
        required: true,
        options: ["Very satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very dissatisfied"],
      },
      {
        id: "field-ease-of-use",
        type: "radio",
        label: "How easy was it to use our product/service?",
        required: true,
        options: ["Very easy", "Easy", "Neutral", "Difficult", "Very difficult"],
      },
      {
        id: "field-expectations",
        type: "radio",
        label: "Did our product/service meet your expectations?",
        required: true,
        options: [
          "Exceeded expectations",
          "Met expectations",
          "Somewhat met expectations",
          "Did not meet expectations",
        ],
      },
      {
        id: "field-improvement",
        type: "textarea",
        label: "How can we improve your experience?",
        placeholder: "Please share your suggestions",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Feedback",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your feedback! We value your opinion.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-03-01T09:45:00Z",
    complexity: "simple",
  },

  // Star Rating Survey
  {
    id: "template-star-rating",
    title: "Star Rating Survey",
    description: "Collect feedback with a visual star rating system",
    coverImage: "https://images.pexels.com/photos/7432/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name",
        type: "text",
        label: "Your Name",
        placeholder: "Enter your name",
        required: false,
      },
      {
        id: "field-email",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-product-rating",
        type: "rating",
        label: "How would you rate our product?",
        required: true,
        options: ["1", "2", "3", "4", "5"],
      },
      {
        id: "field-service-rating",
        type: "rating",
        label: "How would you rate our customer service?",
        required: true,
        options: ["1", "2", "3", "4", "5"],
      },
      {
        id: "field-website-rating",
        type: "rating",
        label: "How would you rate our website experience?",
        required: true,
        options: ["1", "2", "3", "4", "5"],
      },
      {
        id: "field-comments",
        type: "textarea",
        label: "Additional Comments",
        placeholder: "Please share any additional feedback",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Ratings",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f8f9fa",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "Thank you for your ratings! Your feedback helps us improve.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-02-20T10:15:00Z",
    complexity: "simple",
    featured: true,
  },

  // Multi-step Registration Form
  {
    id: "template-multi-step",
    title: "Multi-step Registration",
    description: "A comprehensive registration form with multiple steps",
    coverImage:
      "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      // Step 1: Personal Information
      {
        id: "field-step-1",
        type: "step",
        label: "Personal Information",
        required: false,
      },
      {
        id: "field-first-name",
        type: "text",
        label: "First Name",
        placeholder: "Enter your first name",
        required: true,
      },
      {
        id: "field-last-name",
        type: "text",
        label: "Last Name",
        placeholder: "Enter your last name",
        required: true,
      },
      {
        id: "field-email-multi",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-phone-multi",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
      },
      // Step 2: Account Details
      {
        id: "field-step-2",
        type: "step",
        label: "Account Details",
        required: false,
      },
      {
        id: "field-username",
        type: "text",
        label: "Username",
        placeholder: "Choose a username",
        required: true,
      },
      {
        id: "field-password",
        type: "password",
        label: "Password",
        placeholder: "Create a password",
        required: true,
        helpText: "Must be at least 8 characters with a number and special character",
      },
      {
        id: "field-confirm-password",
        type: "password",
        label: "Confirm Password",
        placeholder: "Confirm your password",
        required: true,
      },
      // Step 3: Preferences
      {
        id: "field-step-3",
        type: "step",
        label: "Preferences",
        required: false,
      },
      {
        id: "field-interests-multi",
        type: "checkbox",
        label: "What are you interested in?",
        required: true,
        options: ["Technology", "Business", "Design", "Marketing", "Education", "Other"],
      },
      {
        id: "field-communication",
        type: "radio",
        label: "How would you like to receive updates?",
        required: true,
        options: ["Email", "SMS", "Both", "None"],
      },
      {
        id: "field-terms",
        type: "checkbox",
        label: "Terms and Conditions",
        required: true,
        options: ["I agree to the terms and conditions"],
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Complete Registration",
      variant: "default",
      size: "lg",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f5f8fa",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Registration complete! Welcome to our platform.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "business",
    createdAt: "2024-03-10T14:30:00Z",
    complexity: "advanced",
    featured: true,
  },

  // Slider-based Survey
  {
    id: "template-slider-survey",
    title: "Slider-based Survey",
    description: "Collect feedback using interactive sliders",
    coverImage:
      "https://images.pexels.com/photos/7176026/pexels-photo-7176026.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-email-slider",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-satisfaction-slider",
        type: "slider",
        label: "How satisfied are you with our product?",
        required: true,
        validation: {
          min: 0,
          max: 10,
        },
        helpText: "0 = Not at all satisfied, 10 = Extremely satisfied",
      },
      {
        id: "field-usability-slider",
        type: "slider",
        label: "How easy is our product to use?",
        required: true,
        validation: {
          min: 0,
          max: 10,
        },
        helpText: "0 = Very difficult, 10 = Very easy",
      },
      {
        id: "field-value-slider",
        type: "slider",
        label: "How would you rate the value for money?",
        required: true,
        validation: {
          min: 0,
          max: 10,
        },
        helpText: "0 = Poor value, 10 = Excellent value",
      },
      {
        id: "field-recommendation-slider",
        type: "slider",
        label: "How likely are you to recommend us to others?",
        required: true,
        validation: {
          min: 0,
          max: 10,
        },
        helpText: "0 = Not at all likely, 10 = Extremely likely",
      },
      {
        id: "field-feedback-slider",
        type: "textarea",
        label: "What could we improve?",
        placeholder: "Please share your suggestions",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Feedback",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f0f4f8",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "Thank you for your feedback! We appreciate your input.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-03-05T11:20:00Z",
    complexity: "medium",
    featured: true,
  },

  // Quick Poll Template
  {
    id: "template-quick-poll",
    title: "Quick Poll",
    description: "Create a simple poll to gather opinions quickly",
    coverImage: "https://images.pexels.com/photos/13594042/pexels-photo-13594042.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-poll-question",
        type: "heading",
        label: "Which feature should we develop next?",
        required: false,
      },
      {
        id: "field-poll-options",
        type: "radio",
        label: "Choose one option:",
        required: true,
        options: [
          "Mobile app integration",
          "Advanced reporting dashboard",
          "Team collaboration tools",
          "AI-powered recommendations",
          "Custom themes and branding",
        ],
      },
      {
        id: "field-email-poll",
        type: "email",
        label: "Email Address (optional)",
        placeholder: "Enter your email to receive poll results",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Vote Now",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f5f5f5",
      inputStyle: "filled",
    },
    settings: {
      successMessage: "Thanks for voting! We'll consider your input.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: false,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-02-25T09:30:00Z",
    complexity: "simple",
  },

  // Image Choice Survey
  {
    id: "template-image-choice",
    title: "Image Choice Survey",
    description: "Let users select options with visual images",
    coverImage:
      "https://images.pexels.com/photos/1269968/pexels-photo-1269968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-name-image",
        type: "text",
        label: "Your Name",
        placeholder: "Enter your name",
        required: true,
      },
      {
        id: "field-email-image",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-design-preference",
        type: "image-choice",
        label: "Which design style do you prefer?",
        required: true,
        options: ["Minimalist", "Modern", "Classic", "Colorful"],
      },
      {
        id: "field-color-scheme",
        type: "image-choice",
        label: "Which color scheme do you prefer?",
        required: true,
        options: ["Blue & White", "Earth Tones", "Vibrant Colors", "Monochrome"],
      },
      {
        id: "field-layout-preference",
        type: "image-choice",
        label: "Which layout works best for you?",
        required: true,
        options: ["Grid Layout", "List View", "Card Layout", "Magazine Style"],
      },
      {
        id: "field-comments-image",
        type: "textarea",
        label: "Additional Comments",
        placeholder: "Any other design preferences?",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Preferences",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f8f9fa",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for sharing your preferences!",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-03-15T13:45:00Z",
    complexity: "medium",
  },

  // Conditional Logic Form
  {
    id: "template-conditional-logic",
    title: "Conditional Logic Form",
    description: "Dynamic form that changes based on user responses",
    coverImage: "https://images.pexels.com/photos/1918219/pexels-photo-1918219.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-customer-type",
        type: "radio",
        label: "Are you a new or existing customer?",
        required: true,
        options: ["New Customer", "Existing Customer"],
      },
      // Fields shown only to new customers
      {
        id: "field-how-heard",
        type: "select",
        label: "How did you hear about us?",
        required: true,
        options: ["Search Engine", "Social Media", "Friend/Referral", "Advertisement", "Other"],
        conditional: {
          field: "field-customer-type",
          value: "New Customer",
        },
      },
      {
        id: "field-interest-reason",
        type: "textarea",
        label: "What made you interested in our products/services?",
        placeholder: "Please share your thoughts",
        required: false,
        conditional: {
          field: "field-customer-type",
          value: "New Customer",
        },
      },
      // Fields shown only to existing customers
      {
        id: "field-customer-id",
        type: "text",
        label: "Customer ID (if known)",
        placeholder: "Enter your customer ID",
        required: false,
        conditional: {
          field: "field-customer-type",
          value: "Existing Customer",
        },
      },
      {
        id: "field-last-purchase",
        type: "select",
        label: "When was your last purchase?",
        required: true,
        options: ["Within the last month", "1-3 months ago", "3-6 months ago", "6-12 months ago", "Over a year ago"],
        conditional: {
          field: "field-customer-type",
          value: "Existing Customer",
        },
      },
      {
        id: "field-satisfaction",
        type: "radio",
        label: "How satisfied are you with our products/services?",
        required: true,
        options: ["Very satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very dissatisfied"],
        conditional: {
          field: "field-customer-type",
          value: "Existing Customer",
        },
      },
      // Common fields for all users
      {
        id: "field-name-conditional",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
      },
      {
        id: "field-email-conditional",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-product-interest",
        type: "checkbox",
        label: "Which products are you interested in?",
        required: true,
        options: ["Product A", "Product B", "Product C", "Service A", "Service B"],
      },
      {
        id: "field-contact-preference",
        type: "radio",
        label: "How would you prefer to be contacted?",
        required: true,
        options: ["Email", "Phone", "No contact please"],
      },
      {
        id: "field-phone-conditional",
        type: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        conditional: {
          field: "field-contact-preference",
          value: "Phone",
        },
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: false,
      position: "center",
    },
    appearance: {
      backgroundType: "none",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your submission!",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "business",
    createdAt: "2024-03-20T10:30:00Z",
    complexity: "advanced",
  },

  // Matrix/Grid Survey
  {
    id: "template-matrix-survey",
    title: "Matrix Survey",
    description: "Collect feedback using a matrix/grid format",
    coverImage:
      "https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    fields: [
      {
        id: "field-email-matrix",
        type: "email",
        label: "Email Address",
        placeholder: "Enter your email",
        required: true,
      },
      {
        id: "field-matrix-intro",
        type: "heading",
        label: "Please rate the following aspects of our service:",
        required: false,
      },
      {
        id: "field-matrix-quality",
        type: "matrix",
        label: "Product Quality",
        required: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
      },
      {
        id: "field-matrix-price",
        type: "matrix",
        label: "Price",
        required: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
      },
      {
        id: "field-matrix-support",
        type: "matrix",
        label: "Customer Support",
        required: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
      },
      {
        id: "field-matrix-usability",
        type: "matrix",
        label: "Ease of Use",
        required: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
      },
      {
        id: "field-matrix-delivery",
        type: "matrix",
        label: "Delivery Speed",
        required: true,
        options: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
      },
      {
        id: "field-comments-matrix",
        type: "textarea",
        label: "Additional Comments",
        placeholder: "Please share any additional feedback",
        required: false,
      },
    ],
    audienceId: null,
    buttonCustomization: {
      text: "Submit Ratings",
      variant: "default",
      size: "default",
      fullWidth: true,
      rounded: true,
      position: "center",
    },
    appearance: {
      backgroundType: "color",
      backgroundColor: "#f5f8fa",
      inputStyle: "bordered",
    },
    settings: {
      successMessage: "Thank you for your feedback! We appreciate your ratings.",
      enableCaptcha: true,
      storeResponses: true,
      allowMultipleSubmissions: true,
    },
    published: false,
    category: "feedback",
    createdAt: "2024-03-12T14:15:00Z",
    complexity: "advanced",
  },
]
